# *Importing Libarary*

In [6]:
import numpy as np

# np.array Method

In [8]:
print(np.array([1,2,5,6]))
print(np.array([1,2,5,6],ndmin=5))
print(np.array([1,2,5,6],dtype=float))
print(np.array([1,2,5,6],dtype=complex))

[1 2 5 6]
[[[[[1 2 5 6]]]]]
[1. 2. 5. 6.]
[1.+0.j 2.+0.j 5.+0.j 6.+0.j]


# Open csv file

In [11]:
file1=open("file1.csv","r")
str1=file1.read()
list1=str1.split(",")
print(list1)
print(np.array(list1,int))

['54', '8', '6', '10', '15', '89', '14']
[54  8  6 10 15 89 14]


# astype method

In [13]:
array1=np.array([1,2.8,5.3,6.4])
print(array1)
print(array1.astype(int))
print(array1.astype('i'))

[1.  2.8 5.3 6.4]
[1 2 5 6]
[1 2 5 6]


# arange method

In [17]:
array1=np.arange(1,10,2,dtype=int)
array2=array1[np.newaxis]
print(array2.shape)
print(array2)

(1, 5)
[[1 3 5 7 9]]


# Random Values

### Generate random scaler values

In [20]:
print(np.random.rand())
print(np.random.randn())
print(np.random.randint(100))

0.5934011424151276
-1.4388065575953475
11


### Generate random vector values

In [21]:
print(np.random.rand(3))
print(np.random.randn(3))
print(np.random.randint(1,100,3))

[0.85231448 0.42290105 0.9594674 ]
[-0.14119909  1.00050082  0.04528907]
[35 28 67]


### Generate random matrix values

In [24]:
print(np.random.rand(3,2))
print(np.random.randn(3,2))
print(np.random.randint(100,size=(3,2)))

[[0.20806617 0.39294913]
 [0.58777041 0.16986064]
 [0.97467347 0.44566348]]
[[-1.52266553  0.02010539]
 [ 0.27680253  0.8901537 ]
 [-0.3031807  -0.37198329]]
[[90 13]
 [45 46]
 [75 23]]


### Generate random tensor values

In [25]:
print(np.random.rand(3,2,4))
print(np.random.randn(3,2,4))
print(np.random.randint(100,size=(3,2,4)))

[[[0.18170633 0.57918713 0.69847925 0.14484708]
  [0.43206505 0.76181338 0.40642814 0.98061451]]

 [[0.44016845 0.80076951 0.78966876 0.56078957]
  [0.63048629 0.57940529 0.60139307 0.29296708]]

 [[0.60089401 0.1126369  0.7312053  0.97213502]
  [0.60495794 0.90878806 0.42466784 0.83965535]]]
[[[ 1.46319853 -0.62476632  0.59951239 -1.41166146]
  [-0.52863591  0.64773852 -0.5473722   2.28030289]]

 [[-0.78688682 -0.11491055 -0.04946051  2.70209739]
  [ 1.0478312   1.67130897  0.04554214 -1.22033456]]

 [[-0.90304336  0.10619547  0.08222064  0.42029044]
  [-1.17384409  0.64281933  1.4831966   0.41104947]]]
[[[78 56 32 33]
  [93 95 90  0]]

 [[30 46 49 91]
  [95 15  7 84]]

 [[97 10 37 95]
  [18 75 27 19]]]


# Zero value

### Generate zero vector value

In [26]:
print(np.zeros(3))
print(np.zeros(3,dtype=int))

[0. 0. 0.]
[0 0 0]


### Generate zero matrix value

In [29]:
print(np.zeros((3,6)))
print(np.zeros((3,6),dtype=int))

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


### Generate zero matrix value

In [30]:
print(np.zeros((3,6,7)))
print(np.zeros((3,6,7),dtype=int))

[[[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]]
[[[0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]]]


# One values

In [32]:
print(np.ones(2))
print(100 * "*")
print(np.ones((2,3)))

print(100 * "*")
print(np.ones((2,3,4),dtype=int))

[1. 1.]
****************************************************************************************************
[[1. 1. 1.]
 [1. 1. 1.]]
****************************************************************************************************
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


# Full values

In [33]:
print(np.full(3,4,dtype=int))
print(100 * "/")
print(np.full((3,5),6,dtype=int))
print(100 * "/")
print(np.full((3,5,2),3,dtype=int))


[4 4 4]
////////////////////////////////////////////////////////////////////////////////////////////////////
[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]
////////////////////////////////////////////////////////////////////////////////////////////////////
[[[3 3]
  [3 3]
  [3 3]
  [3 3]
  [3 3]]

 [[3 3]
  [3 3]
  [3 3]
  [3 3]
  [3 3]]

 [[3 3]
  [3 3]
  [3 3]
  [3 3]
  [3 3]]]


# Like values

In [35]:
vector1=np.random.randint(1,20,100,dtype=int)
print(vector1)
print(100* "*")
print(np.ones_like(vector1))
print(100* "*")
print(np.zeros_like(vector1))
print(100* "*")
print(np.full_like(vector1,45))

[16  4  5 18 12  6 17 15  8 18 13 18  2  3  7  8 17 12 17 11 12 11 12  7
 13 11  7  7  3 17  3  8 14  7  8  2  8 12 15  9 10 17  1 10 14  9  1 14
  1 16  1  8  5  3 12  4  2  9  4 14 19  4  8 12 17  6 18  9 14 15  4 16
 16 10 13  1  8 16 18 14 13 18 19 10  8 14 14 10 12 12  3 17  9  2  4  2
 12  4  9  1]
****************************************************************************************************
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
****************************************************************************************************
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
************************************************************************************

# identity matrix

In [36]:
print(np.identity(10))
print(100* "*")
print(np.identity(10,dtype=int))

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
****************************************************************************************************
[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]


# Transpose matrix

In [38]:
mat=np.random.randint(1,10,(2,3))
print(mat)
print(100* "*")
print(mat.transpose())
print(100* "*")
print(mat.T)

[[2 8 9]
 [8 7 7]]
****************************************************************************************************
[[2 8]
 [8 7]
 [9 7]]
****************************************************************************************************
[[2 8]
 [8 7]
 [9 7]]


# Row and Column matrix

In [39]:
print(np.arange(1,10,2))
print(100* "*")
print(np.arange(1,10,2).T)

[1 3 5 7 9]
****************************************************************************************************
[1 3 5 7 9]


# Lower triangle matrix

In [41]:
mat = np.random.randint(1,10,(5,5))
print(np.tril(mat))
print(100* "*")
print(np.tril(mat,-1))

[[9 0 0 0 0]
 [6 3 0 0 0]
 [9 5 6 0 0]
 [8 1 3 7 0]
 [7 3 8 9 8]]
****************************************************************************************************
[[0 0 0 0 0]
 [6 0 0 0 0]
 [9 5 0 0 0]
 [8 1 3 0 0]
 [7 3 8 9 0]]


# Upper triangle matrix

In [43]:
mat = np.random.randint(4,14,(4,4))
print(np.triu(mat))
print(100* "*")
print(np.triu(mat,+1))

[[ 6 10 11  9]
 [ 0 12  5  9]
 [ 0  0 12  7]
 [ 0  0  0  9]]
****************************************************************************************************
[[ 0 10 11  9]
 [ 0  0  5  9]
 [ 0  0  0  7]
 [ 0  0  0  0]]


# Symmetrical matrix    

In [48]:
mat= np.random.randint(10,size=(4,4))
print(mat)
print(100* "*")
symetrical= np.tril(mat)+np.tril(mat).T
print(symetrical)

[[4 2 7 1]
 [3 4 1 6]
 [4 4 7 0]
 [8 0 0 8]]
****************************************************************************************************
[[ 8  3  4  8]
 [ 3  8  4  0]
 [ 4  4 14  0]
 [ 8  0  0 16]]


# Digonal and Digonal matrix

In [52]:
mat = np.random.randint(1,100,(8,8))
print(mat)
print(100* "*")
print(np.diag(mat))  #Diagonal
print(100* "*")
print(np.diag([5,6,3,9])) #Diagonal matrix


[[ 7 98  6 29 35 68 30 85]
 [40 67 20 53  4 66 90 81]
 [ 9 58 35  3  8 77 26 15]
 [63 49 80 37 14 21 59 16]
 [69  1 80  7  6 28 69 67]
 [20 43 50 64 36 32 47 30]
 [62 43 98 38 53 34 25 27]
 [80  6 13 22 23 75 64 38]]
****************************************************************************************************
[ 7 67 35 37  6 32 25 38]
****************************************************************************************************
[[5 0 0 0]
 [0 6 0 0]
 [0 0 3 0]
 [0 0 0 9]]


# nditer method

In [61]:
mat = np.arange(1,27,3).reshape(3,3)
print(mat)

for row in mat:
    for col in row:
        print(col)

print(100* "*")

for i in np.nditer(mat):
    print(i)

print(100* "*")

mat2 = np.array([10,3,6],ndmin=5)
print(mat2)
print(100* "*")

for i in np.nditer(mat2):
    print(i)


[[ 1  4  7]
 [10 13 16]
 [19 22 25]]
1
4
7
10
13
16
19
22
25
****************************************************************************************************
1
4
7
10
13
16
19
22
25
****************************************************************************************************
[[[[[10  3  6]]]]]
****************************************************************************************************
10
3
6
