In [1]:
import numpy as np

# Adition , Subtraction and Multiplication of vector

In [5]:

a=np.arange(10,dtype=int)
b=np.arange(1,20,2,dtype=int)
print(a)
print(10* "-")
print(b)
print(10* "-")

print(a**b)
print(10* "-")

print(a-b)
print(10* "-")
print(a/b)
print(10* "-")
print(a//b)
print(10* "-")
print(a<b)
print(10* "-")
print(a*b)
print(10* "-")

print(np.multiply(a,b))
print(10* "-")
print(np.add(a,b))
print(10* "-")
print(np.subtract(a,b))
print(10* "-")
print(np.divide(a,b))
print(10* "-")


[0 1 2 3 4 5 6 7 8 9]
----------
[ 1  3  5  7  9 11 13 15 17 19]
----------
[         0          1         32       2187     262144   48828125
  175792128 1622647863          0 -400556711]
----------
[ -1  -2  -3  -4  -5  -6  -7  -8  -9 -10]
----------
[0.         0.33333333 0.4        0.42857143 0.44444444 0.45454545
 0.46153846 0.46666667 0.47058824 0.47368421]
----------
[0 0 0 0 0 0 0 0 0 0]
----------
[ True  True  True  True  True  True  True  True  True  True]
----------
[  0   3  10  21  36  55  78 105 136 171]
----------
[  0   3  10  21  36  55  78 105 136 171]
----------
[ 1  4  7 10 13 16 19 22 25 28]
----------
[ -1  -2  -3  -4  -5  -6  -7  -8  -9 -10]
----------
[0.         0.33333333 0.4        0.42857143 0.44444444 0.45454545
 0.46153846 0.46666667 0.47058824 0.47368421]
----------


# Adition , Subtraction and Multiplication of matrix

In [7]:

a=np.random.randint(1,10,size=(2,5),dtype=int)
b=np.random.randint(1,10,size=(2,5),dtype=int)
print(a)
print(10* "-")
print(b)
print(10* "-")

print(a-b)
print(10* "-")
print(a+b)
print(10* "-")
print(a*b) # incorrect
print(10* "-")

c=np.random.randint(1,10,size=(5,6),dtype=int)

print(np.dot(a,c))


[[5 9 6 3 7]
 [1 5 2 2 5]]
----------
[[9 9 2 1 9]
 [1 3 4 1 6]]
----------
[[-4  0  4  2 -2]
 [ 0  2 -2  1 -1]]
----------
[[14 18  8  4 16]
 [ 2  8  6  3 11]]
----------
[[45 81 12  3 63]
 [ 1 15  8  2 30]]
----------
[[113 145 164 103 204 172]
 [ 61  69  87  51 104  95]]


# Sum , Min , Max , Average , Size , Sqrt , Square of vector and matrix

In [14]:
mat1= np.random.randint(1,10,(2,5))
print(mat1.sum())
print(10 * "%%")
print(mat1.min())
print(10 * "%%")
print(mat1.max())
print(10 * "%%")
print(mat1.mean())
print(10 * "%%")
print(mat1.std())
print(10 * "%%")
print(np.average(mat1))
print(10 * "%%")
print(np.size(mat1))


vect1=np.array([5,6,3,8])
print(np.sqrt(vect1))
print(10 * "%%")
print(np.square(vect1))

mat2=np.array([[5,6,3,8],[9,8,7,4]])
print(np.sqrt(mat2))
print(10 * "%%")
print(np.square(mat2))

55
%%%%%%%%%%%%%%%%%%%%
1
%%%%%%%%%%%%%%%%%%%%
9
%%%%%%%%%%%%%%%%%%%%
5.5
%%%%%%%%%%%%%%%%%%%%
2.3769728648009427
%%%%%%%%%%%%%%%%%%%%
5.5
%%%%%%%%%%%%%%%%%%%%
10
[2.23606798 2.44948974 1.73205081 2.82842712]
%%%%%%%%%%%%%%%%%%%%
[25 36  9 64]
[[2.23606798 2.44948974 1.73205081 2.82842712]
 [3.         2.82842712 2.64575131 2.        ]]
%%%%%%%%%%%%%%%%%%%%
[[25 36  9 64]
 [81 64 49 16]]


# Eigenvalues & Eigenvector

In [16]:
mat=np.array([[5,4,6],[3,2,7],[5,3,4]])
print(mat)
print(15*"-")
w,v = np.linalg.eig(mat)
print(w)
print(v)

[[5 4 6]
 [3 2 7]
 [5 3 4]]
---------------
[13.04058073+0.j         -1.02029036+0.75456299j -1.02029036-0.75456299j]
[[ 0.66155734+0.j         -0.30565957-0.23002898j -0.30565957+0.23002898j]
 [ 0.52144898+0.j          0.87001604+0.j          0.87001604-0.j        ]
 [ 0.53891822+0.j         -0.24438891+0.19236698j -0.24438891-0.19236698j]]


# Matrix determinant and inverse and Adjoint

In [20]:
mat=np.array([[2,1],[3,6]],dtype=int)
print(mat)
print(15*'-')
det=np.linalg.det(mat)
print(det)
print(15*'-')
inv=np.linalg.inv(mat)
print(15*'-')
print(inv*det)

[[2 1]
 [3 6]]
---------------
9.000000000000002
---------------
---------------
[[ 6. -1.]
 [-3.  2.]]


# Matrix norm

In [25]:
vect1= np.array([3,2,10,6])
print(np.linalg.norm(vect1))
print(20* '*')
print(np.linalg.norm(vect1,keepdims=True))
print(20* '*')

mat=np.array([[3,2],[10,6]])
print(mat)
print(20* '*')
print(np.linalg.norm(mat))
print(20* '*')
print(np.linalg.norm(mat,axis=0))
print(20* '*')
print(np.linalg.norm(mat,axis=1))
print(20* '*')
print(np.linalg.norm(mat,keepdims=True))

12.206555615733702
********************
[12.20655562]
********************
[[ 3  2]
 [10  6]]
********************
12.206555615733702
********************
[10.44030651  6.32455532]
********************
[ 3.60555128 11.66190379]
********************
[[12.20655562]]


# Euclidean distance

In [30]:
# three method

#1
a=np.array([[3,2],[10,6]])
b=np.array([[10,2],[5,9]])
print(20* '*')
print(np.linalg.norm(a-b))

#2  only for vector
c=np.array([3,2,10,6])
d=np.array([10,2,5,9])
print(20* '*')
temp =c-d
sum_sq = np.dot(temp.T,temp)
print(np.sqrt(sum_sq))

#3
print(20* '*')
t=a-b
sq=np.square(t)
sum_sq=np.sum(sq)
sqrt=np.sqrt(sum_sq)
print(sqrt)

********************
9.1104335791443
********************
9.1104335791443
********************
9.1104335791443


# Resolve

In [34]:
a=np.array([[2,5,6],[3,-1,6],[5,-5,4]])
b=np.array([3,8,-2])
print(np.linalg.solve(a,b))

[-4.80487805 -1.63414634  3.46341463]
